In [1]:
import pandas as pd

df = pd.read_csv('ship_fuel_efficiency.csv')

df.head()

,ship_id,ship_type,route_id,month,distance,fuel_type,fuel_consumption,CO2_emissions,weather_conditions,engine_efficiency
0,NG001,Oil Service Boat,Warri-Bonny,January,132.26,HFO,3779.77,10625.76,Stormy,92.14
1,NG001,Oil Service Boat,Port Harcourt-Lagos,February,128.52,HFO,4461.44,12779.73,Moderate,92.98
2,NG001,Oil Service Boat,Port Harcourt-Lagos,March,67.30,HFO,1867.73,5353.01,Calm,87.61
3,NG001,Oil Service Boat,Port Harcourt-Lagos,April,71.68,Diesel,2393.51,6506.52,Stormy,87.42
4,NG001,Oil Service Boat,Lagos-Apapa,May,134.32,HFO,4267.19,11617.03,Calm,85.61

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1440 entries, 0 to 1439
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ship_id             1440 non-null   object
 1   ship_type           1440 non-null   object
 2   route_id            1440 non-null   object
 3   month               1440 non-null   object
 4   distance            1440 non-null   float64
 5   fuel_type           1440 non-null   object
 6   fuel_consumption    1440 non-null   float64
 7   CO2_emissions       1440 non-null   float64
 8   weather_conditions  1440 non-null   object
 9   engine_efficiency   1440 non-null   float64
dtypes: float64(4), object(6)
memory usage: 112.6+ KB

In [3]:
df.describe()

          distance  fuel_consumption  CO2_emissions  engine_efficiency
count  1440.000000       1440.000000    1440.000000        1440.000000
mean    151.753354       4844.246535   13365.454882          82.582924
std     108.472230       4892.352813   13567.650118           7.158289
min      20.080000        237.880000     615.680000          70.010000
25%      79.002500       1837.962500    4991.485000          76.255000
50%     123.465000       3060.880000    8423.255000          82.775000
75%     180.780000       4870.675000   13447.120000          88.862500
max     498.550000      24648.520000   71871.210000          94.980000

In [4]:
df.isnull().sum()

ship_id               0
ship_type             0
route_id              0
month                 0
distance              0
fuel_type             0
fuel_consumption      0
CO2_emissions         0
weather_conditions    0
engine_efficiency     0
dtype: int64

In [5]:
df['fuel_per_nm'] = df['fuel_consumption'] / df['distance']
df['co2_per_nm'] = df['CO2_emissions'] / df['distance']

df[['ship_id','distance','fuel_consumption','fuel_per_nm','co2_per_nm']]

     ship_id  distance  fuel_consumption  fuel_per_nm  co2_per_nm
0      NG001    132.26           3779.77    28.578331   80.339936
1      NG001    128.52           4461.44    34.713974   99.437675
2      NG001     67.30           1867.73    27.752303   79.539525
3      NG001     71.68           2393.51    33.391602   90.771763
4      NG001    134.32           4267.19    31.768836   86.487716
...      ...       ...               ...          ...         ...
1435   NG120     63.84           1633.85    25.592888   76.006892
1436   NG120     61.43           1263.48    20.567801   58.133322
1437   NG120    193.09           4661.63    24.142265   63.530633
1438   NG120    166.50           4298.00    25.813814   73.860120
1439   NG120    127.66           3549.91    27.807536   83.361272

[1440 rows x 5 columns]

In [6]:
ship_dimension = df[['ship_id','ship_type','fuel_type']].drop_duplicates().reset_index(drop=True)
ship_dimension

    ship_id         ship_type fuel_type
0     NG001  Oil Service Boat       HFO
1     NG001  Oil Service Boat    Diesel
2     NG002   Fishing Trawler       HFO
3     NG002   Fishing Trawler    Diesel
4     NG003  Oil Service Boat       HFO
..      ...               ...       ...
208   NG118       Tanker Ship    Diesel
209   NG119       Tanker Ship       HFO
210   NG119       Tanker Ship    Diesel
211   NG120   Fishing Trawler    Diesel
212   NG120   Fishing Trawler       HFO

[213 rows x 3 columns]

In [7]:
route_dimension = df[['route_id']].drop_duplicates().reset_index(drop=True)
route_dimension

              route_id
0          Warri-Bonny
1  Port Harcourt-Lagos
2          Lagos-Apapa
3       Escravos-Lagos

In [8]:
df.describe()

,distance,fuel_consumption,CO2_emissions,engine_efficiency,fuel_per_nm,co2_per_nm
count,1440.000000,1440.000000,1440.000000,1440.000000,1440.000000,1440.000000
mean,151.753354,4844.246535,13365.454882,82.582924,28.644927,78.853495
std,108.472230,4892.352813,13567.650118,7.158289,9.967580,27.962900
min,20.080000,237.880000,615.680000,70.010000,10.000000,25.648843
25%,79.002500,1837.962500,4991.485000,76.255000,21.153766,58.644972
50%,123.465000,3060.880000,8423.255000,82.775000,28.772703,79.185258
75%,180.780000,4870.675000,13447.120000,88.862500,34.236833,94.950509
max,498.550000,24648.520000,71871.210000,94.980000,49.957811,146.628060

In [9]:
def fuel_grade(fuel):
    if fuel < 21.1:
        return 'A'
    elif fuel < 34.2:
        return 'B'
    else:
        return 'C'

df['eff_grade'] = df['fuel_per_nm'].apply(fuel_grade)

In [10]:
def co2_grade(co2):
    if co2 < 58.6:
        return 'A'
    elif co2 < 95.0:
        return 'B'
    else:
        return 'C'

df['co2_grade'] = df['co2_per_nm'].apply(co2_grade)

In [11]:
df.groupby('fuel_type')[['fuel_per_nm','co2_per_nm']].mean()

           fuel_per_nm  co2_per_nm
fuel_type
Diesel       26.448423   72.774680
HFO          32.294941   88.954892

In [12]:
fuel_fact = df[['ship_id','route_id','month','distance','fuel_consumption','CO2_emissions','weather_conditions','engine_efficiency','fuel_per_nm','co2_per_nm','eff_grade','co2_grade']]

fuel_fact

,ship_id,route_id,month,distance,fuel_consumption,CO2_emissions,weather_conditions,engine_efficiency,fuel_per_nm,co2_per_nm,eff_grade,co2_grade
0,NG001,Warri-Bonny,January,132.26,3779.77,10625.76,Stormy,92.14,28.578331,80.339936,B,B
1,NG001,Port Harcourt-Lagos,February,128.52,4461.44,12779.73,Moderate,92.98,34.713974,99.437675,C,C
2,NG001,Port Harcourt-Lagos,March,67.30,1867.73,5353.01,Calm,87.61,27.752303,79.539525,B,B
3,NG001,Port Harcourt-Lagos,April,71.68,2393.51,6506.52,Stormy,87.42,33.391602,90.771763,B,B
4,NG001,Lagos-Apapa,May,134.32,4267.19,11617.03,Calm,85.61,31.768836,86.487716,B,B
...,...,...,...,...,...,...,...,...,...,...,...,...
1435,NG120,Port Harcourt-Lagos,August,63.84,1633.85,4852.28,Stormy,75.88,25.592888,76.006892,B,B
1436,NG120,Lagos-Apapa,September,61.43,1263.48,3571.13,Calm,78.00,20.567801,58.133322,A,A
1437,NG120,Port Harcourt-Lagos,October,193.09,4661.63,12267.13,Stormy,79.67,24.142265,63.530633,B,B
1438,NG120,Lagos-Apapa,November,166.50,4298.00,12297.71,Moderate,92.87,25.813814,73.860120,B,B
1439,NG120,Warri-Bonny,December,127.66,3549.91,10641.90,Moderate,90.82,27.807536,83.361272,B,B

In [21]:
!apt-get -y -qq update
!apt-get -y -qq install postgresql
!service postgresql start

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Preconfiguring packages ...
Selecting previously unselected package logrotate.
(Reading database ... 118243 files and directories currently installed.)
Preparing to unpack .../00-logrotate_3.19.0-1ubuntu1.1_amd64.deb ...
Unpacking logrotate (3.19.0-1ubuntu1.1) ...
Selecting previously unselected package netbase.
Preparing to unpack .../01-netbase_6.3_all.deb ...
Unpacking netbase (6.3) ...
Selecting previously unselected package libcommon-sense-perl:amd64.
Preparing to unpack .../02-libcommon-sense-perl_3.75-2build1_amd64.deb ...
Unpacking libcommon-sense-perl:amd64 (3.75-2build1) ...
Selecting previously unselected package libjson-perl.
Preparing to unpack .../03-libjson-perl_4.04000-1_all.deb ...
Unpacking libjson-perl (4.04000-1) ...
Selecting previously unselected package libtypes-serialiser-perl.
Preparing to unpack .../04-libtypes-serialiser-perl_1.01-1_all.deb ...
Unpacking libtypes-serialiser-perl (1.01-1) ...
Selecting previously unselected package libjson-xs-perl.
Preparing to unpack .../05-libjson-xs-perl_4.040-0ubuntu0.22.04.1_amd64.deb ...
Unpacking libjson-xs-perl (4.040-0ubuntu0.22.04.1) ...
Selecting previously unselected package libllvm14:amd64.
Preparing to unpack .../06-libllvm14_1%3a14.0.0-1ubuntu1.1_amd64.deb ...
Unpacking libllvm14:amd64 (1:14.0.0-1ubuntu1.1) ...
Selecting previously unselected package postgresql-client-common.
Preparing to unpack .../07-postgresql-client-common_238_all.deb ...
Unpacking postgresql-client-common (238) ...
Selecting previously unselected package postgresql-client-14.
Preparing to unpack .../08-postgresql-client-14_14.23-0ubuntu0.22.04.1_amd64.deb ...
Unpacking postgresql-client-14 (14.23-0ubuntu0.22.04.1) ...
Selecting previously unselected package ssl-cert.
Preparing to unpack .../09-ssl-cert_1.1.2_all.deb ...
Unpacking ssl-cert (1.1.2) ...
Selecting previously unselected package postgresql-common.
Preparing to unpack .../10-postgresql-common_238_all.deb ...
Adding 'diversion of /usr/bin/pg_config to /usr/bin/pg_config.libpq-dev by postgresql-common'
Unpacking postgresql-common (238) ...
Selecting previously unselected package postgresql-14.
Preparing to unpack .../11-postgresql-14_14.23-0ubuntu0.22.04.1_amd64.deb ...
Unpacking postgresql-14 (14.23-0ubuntu0.22.04.1) ...
Selecting previously unselected package postgresql.
Preparing to unpack .../12-postgresql_14+238_all.deb ...
Unpacking postgresql (14+238) ...
Selecting previously unselected package sysstat.
Preparing to unpack .../13-sysstat_12.5.2-2ubuntu0.2_amd64.deb ...
Unpacking sysstat (12.5.2-2ubuntu0.2) ...
Setting up logrotate (3.19.0-1ubuntu1.1) ...
Created symlink /etc/systemd/system/timers.target.wants/logrotate.timer → /lib/systemd/system/logrotate.timer.
Setting up libcommon-sense-perl:amd64 (3.75-2build1) ...
Setting up ssl-cert (1.1.2) ...
Setting up libllvm14:amd64 (1:14.0.0-1ubuntu1.1) ...
Setting up libtypes-serialiser-perl (1.01-1) ...
Setting up libjson-perl (4.04000-1) ...
Setting up netbase (6.3) ...
Setting up sysstat (12.5.2-2ubuntu0.2) ...

Creating config file /etc/default/sysstat with new version
update-alternatives: using /usr/bin/sar.sysstat to provide /usr/bin/sar (sar) in auto mode
Created symlink /etc/systemd/system/sysstat.service.wants/sysstat-collect.timer → /lib/systemd/system/sysstat-collect.timer.
Created symlink /etc/systemd/system/sysstat.service.wants/sysstat-summary.timer → /lib/systemd/system/sysstat-summary.timer.
Created symlink /etc/systemd/system/multi-user.target.wants/sysstat.service → /lib/systemd/system/sysstat.service.
Setting up postgresql-client-common (238) ...
Setting up libjson-xs-perl (4.040-0ubuntu0.22.04.1) ...
Setting up postgresql-client-14 (14.23-0ubuntu0.22.04.1) ...
update-alternatives: using /usr/share/postgresql/14/man/man1/psql.1.gz to provide /usr/share/man/man1/psql.1.gz (psql.1.gz) in auto mode
Setting up postgresql-common (238) ...
Adding user postgres to group ssl-cert

Creating config file /etc/postgresql-common/createcluster.conf with new version
Building PostgreSQL dictionaries from installed myspell/hunspell packages...
Removing obsolete dictionary files:
Created symlink /etc/systemd/system/multi-user.target.wants/postgresql.service → /lib/systemd/system/postgresql.service.
Setting up postgresql-14 (14.23-0ubuntu0.22.04.1) ...
Creating new PostgreSQL cluster 14/main ...
/usr/lib/postgresql/14/bin/initdb -D /var/lib/postgresql/14/main --auth-local peer --auth-host scram-sha-256 --no-instructions
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/14/main ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok
update-alternatives: using /usr/share/postgresql/14/man/man1/postmaster.1.gz to provide /usr/share/man/man1/postmaster.1.gz (postmaster.1.gz) in auto mode
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up postgresql (14+238) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.13) ...
/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

 * Starting PostgreSQL 14 database server
   ...done.

In [23]:
# 1. 모든 접속 요청을 비밀번호 없이 무조건 신뢰(trust)하도록 설정 파일을 덮어씁니다.
!echo "local   all             all                                     trust" > /etc/postgresql/14/main/pg_hba.conf
!echo "host    all             all             127.0.0.1/32            trust" >> /etc/postgresql/14/main/pg_hba.conf
!echo "host    all             all             ::1/128                 trust" >> /etc/postgresql/14/main/pg_hba.conf

# 2. 변경된 설정을 적용하기 위해 PostgreSQL 서비스를 재시작합니다.
!service postgresql restart

 * Restarting PostgreSQL 14 database server
   ...done.

In [24]:
import os
import urllib.parse
from sqlalchemy import create_engine
from dotenv import load_dotenv

load_dotenv()

db_user = os.getenv("DB_USER")
db_password = os.getenv("DB_PASSWORD")
db_host = os.getenv("DB_HOST")
db_port = os.getenv("DB_PORT")
db_name = os.getenv("DB_NAME")

if db_port is None:
    db_user = "postgres"
    db_password = ""
    db_host = "localhost"
    db_port = "5432"
    db_name = "postgres"


engine = create_engine(f'postgresql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}')

try:
    ship_dimension.to_sql('ship_dimension', engine, if_exists='replace', index=False)
    print("1. ship_dimension 적재 완료!")

    route_dimension.to_sql('route_dimension', engine, if_exists='replace', index=False)
    print("2. route_dimension 적재 완료!")

    fuel_fact.to_sql('fuel_fact', engine, if_exists='replace', index=False)
    print("3. fuel_fact 적재 완료! 최종 ETL 성공!")

except Exception as e:
    print("적재 중 에러 발생:", e)

1. ship_dimension 적재 완료!
2. route_dimension 적재 완료!
3. fuel_fact 적재 완료! 최종 ETL 성공!