In [1]:
import pandas as pd

df = pd.read_csv('ship_fuel_efficiency.csv')

df.head()

,ship_id,ship_type,route_id,month,distance,fuel_type,fuel_consumption,CO2_emissions,weather_conditions,engine_efficiency
0,NG001,Oil Service Boat,Warri-Bonny,January,132.26,HFO,3779.77,10625.76,Stormy,92.14
1,NG001,Oil Service Boat,Port Harcourt-Lagos,February,128.52,HFO,4461.44,12779.73,Moderate,92.98
2,NG001,Oil Service Boat,Port Harcourt-Lagos,March,67.30,HFO,1867.73,5353.01,Calm,87.61
3,NG001,Oil Service Boat,Port Harcourt-Lagos,April,71.68,Diesel,2393.51,6506.52,Stormy,87.42
4,NG001,Oil Service Boat,Lagos-Apapa,May,134.32,HFO,4267.19,11617.03,Calm,85.61

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1440 entries, 0 to 1439
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ship_id             1440 non-null   object
 1   ship_type           1440 non-null   object
 2   route_id            1440 non-null   object
 3   month               1440 non-null   object
 4   distance            1440 non-null   float64
 5   fuel_type           1440 non-null   object
 6   fuel_consumption    1440 non-null   float64
 7   CO2_emissions       1440 non-null   float64
 8   weather_conditions  1440 non-null   object
 9   engine_efficiency   1440 non-null   float64
dtypes: float64(4), object(6)
memory usage: 112.6+ KB

In [3]:
df.describe()

          distance  fuel_consumption  CO2_emissions  engine_efficiency
count  1440.000000       1440.000000    1440.000000        1440.000000
mean    151.753354       4844.246535   13365.454882          82.582924
std     108.472230       4892.352813   13567.650118           7.158289
min      20.080000        237.880000     615.680000          70.010000
25%      79.002500       1837.962500    4991.485000          76.255000
50%     123.465000       3060.880000    8423.255000          82.775000
75%     180.780000       4870.675000   13447.120000          88.862500
max     498.550000      24648.520000   71871.210000          94.980000

In [4]:
df.isnull().sum()

ship_id               0
ship_type             0
route_id              0
month                 0
distance              0
fuel_type             0
fuel_consumption      0
CO2_emissions         0
weather_conditions    0
engine_efficiency     0
dtype: int64

In [5]:
df['fuel_per_nm'] = df['fuel_consumption'] / df['distance']
df['co2_per_nm'] = df['CO2_emissions'] / df['distance']

df[['ship_id','distance','fuel_consumption','fuel_per_nm','co2_per_nm']]

     ship_id  distance  fuel_consumption  fuel_per_nm  co2_per_nm
0      NG001    132.26           3779.77    28.578331   80.339936
1      NG001    128.52           4461.44    34.713974   99.437675
2      NG001     67.30           1867.73    27.752303   79.539525
3      NG001     71.68           2393.51    33.391602   90.771763
4      NG001    134.32           4267.19    31.768836   86.487716
...      ...       ...               ...          ...         ...
1435   NG120     63.84           1633.85    25.592888   76.006892
1436   NG120     61.43           1263.48    20.567801   58.133322
1437   NG120    193.09           4661.63    24.142265   63.530633
1438   NG120    166.50           4298.00    25.813814   73.860120
1439   NG120    127.66           3549.91    27.807536   83.361272

[1440 rows x 5 columns]

In [6]:
ship_dimension = df[['ship_id','ship_type','fuel_type']].drop_duplicates().reset_index(drop=True)
ship_dimension

    ship_id         ship_type fuel_type
0     NG001  Oil Service Boat       HFO
1     NG001  Oil Service Boat    Diesel
2     NG002   Fishing Trawler       HFO
3     NG002   Fishing Trawler    Diesel
4     NG003  Oil Service Boat       HFO
..      ...               ...       ...
208   NG118       Tanker Ship    Diesel
209   NG119       Tanker Ship       HFO
210   NG119       Tanker Ship    Diesel
211   NG120   Fishing Trawler    Diesel
212   NG120   Fishing Trawler       HFO

[213 rows x 3 columns]

In [7]:
route_dimension = df[['route_id']].drop_duplicates().reset_index(drop=True)
route_dimension

              route_id
0          Warri-Bonny
1  Port Harcourt-Lagos
2          Lagos-Apapa
3       Escravos-Lagos

In [8]:
df.describe()

,distance,fuel_consumption,CO2_emissions,engine_efficiency,fuel_per_nm,co2_per_nm
count,1440.000000,1440.000000,1440.000000,1440.000000,1440.000000,1440.000000
mean,151.753354,4844.246535,13365.454882,82.582924,28.644927,78.853495
std,108.472230,4892.352813,13567.650118,7.158289,9.967580,27.962900
min,20.080000,237.880000,615.680000,70.010000,10.000000,25.648843
25%,79.002500,1837.962500,4991.485000,76.255000,21.153766,58.644972
50%,123.465000,3060.880000,8423.255000,82.775000,28.772703,79.185258
75%,180.780000,4870.675000,13447.120000,88.862500,34.236833,94.950509
max,498.550000,24648.520000,71871.210000,94.980000,49.957811,146.628060

In [9]:
def fuel_grade(fuel):
    if fuel < 21.1:
        return 'A'
    elif fuel < 34.2:
        return 'B'
    else:
        return 'C'

df['eff_grade'] = df['fuel_per_nm'].apply(fuel_grade)

In [10]:
def co2_grade(co2):
    if co2 < 58.6:
        return 'A'
    elif co2 < 95.0:
        return 'B'
    else:
        return 'C'

df['co2_grade'] = df['co2_per_nm'].apply(co2_grade)

In [11]:
df.groupby('fuel_type')[['fuel_per_nm','co2_per_nm']].mean()

           fuel_per_nm  co2_per_nm
fuel_type
Diesel       26.448423   72.774680
HFO          32.294941   88.954892

In [12]:
month_map = {'January': 1, 'February': 2, 'March': 3, 'April': 4, 'May': 5, 'June': 6,
             'July': 7, 'August': 8, 'September': 9, 'October': 10, 'November': 11, 'December': 12}

month_data = [{'month':m} for m in df['month'].unique()]
month_dimension = pd.DataFrame(month_data)
month_dimension['month_num'] = month_dimension['month'].map(month_map)
month_dimension['month_id'] = range(1, len(month_dimension) + 1)

fuel_fact = df[['ship_id','route_id','month','distance','fuel_consumption','CO2_emissions','weather_conditions','engine_efficiency','fuel_per_nm','co2_per_nm','eff_grade','co2_grade']]
fuel_fact = fuel_fact.merge(month_dimension[['month','month_id']], on='month', how='left')
fuel_fact = fuel_fact.drop(columns=['month'])

fuel_fact

,ship_id,route_id,distance,fuel_consumption,CO2_emissions,weather_conditions,engine_efficiency,fuel_per_nm,co2_per_nm,eff_grade,co2_grade,month_id
0,NG001,Warri-Bonny,132.26,3779.77,10625.76,Stormy,92.14,28.578331,80.339936,B,B,1
1,NG001,Port Harcourt-Lagos,128.52,4461.44,12779.73,Moderate,92.98,34.713974,99.437675,C,C,2
2,NG001,Port Harcourt-Lagos,67.30,1867.73,5353.01,Calm,87.61,27.752303,79.539525,B,B,3
3,NG001,Port Harcourt-Lagos,71.68,2393.51,6506.52,Stormy,87.42,33.391602,90.771763,B,B,4
4,NG001,Lagos-Apapa,134.32,4267.19,11617.03,Calm,85.61,31.768836,86.487716,B,B,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1435,NG120,Port Harcourt-Lagos,63.84,1633.85,4852.28,Stormy,75.88,25.592888,76.006892,B,B,8
1436,NG120,Lagos-Apapa,61.43,1263.48,3571.13,Calm,78.00,20.567801,58.133322,A,A,9
1437,NG120,Port Harcourt-Lagos,193.09,4661.63,12267.13,Stormy,79.67,24.142265,63.530633,B,B,10
1438,NG120,Lagos-Apapa,166.50,4298.00,12297.71,Moderate,92.87,25.813814,73.860120,B,B,11
1439,NG120,Warri-Bonny,127.66,3549.91,10641.90,Moderate,90.82,27.807536,83.361272,B,B,12

In [13]:
import os
from dotenv import load_dotenv

print("현재 폴더:", os.getcwd())
load_dotenv()
print("DB_HOST:", os.getenv("DB_HOST"))
print("DB_USER:", os.getenv("DB_USER"))

현재 폴더: C:\Users\duatj\Data_Engineer\1st_project
DB_HOST: localhost
DB_USER: postgres

In [ ]:
import os
import urllib.parse
from sqlalchemy import create_engine
from dotenv import load_dotenv

load_dotenv(dotenv_path=r"C:\Data_Engineer\Projects\1st\.env")

db_port = os.getenv("DB_PORT","5434")

print(os.getenv('DB_PORT'))

db_user = os.getenv("DB_USER")
db_password = os.getenv("DB_PASSWORD")
db_host = os.getenv("DB_HOST")
db_port = os.getenv("DB_PORT","5434")
db_name = os.getenv("DB_NAME")

engine = create_engine(f'postgresql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}')

try:
    ship_dimension.to_sql('ship_dimension', engine, if_exists='replace', index=False)
    print("1. Completed loading ship_dimension!")

    route_dimension.to_sql('route_dimension', engine, if_exists='replace', index=False)
    print("2. Completed loading route_dimension!")

    month_dimension.to_sql('month_dimension', engine, if_exists='replace', index=False)
    print("3. Completed loading month_dimension!")

    fuel_fact.to_sql('fuel_fact', engine, if_exists='replace', index=False)
    print("4. Completed loading fuel_fact! Finished loading!")

except Exception as e:
    print("Failed to load:", e)

5432